from __future__ import annotations

from enum import StrEnum


class ApprovalType(StrEnum):
    TASK_START = "TASK_START"


class WorkflowStatus(StrEnum):
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AttemptStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"


class LeaseStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"
    RELEASED = "RELEASED"


class WorkerStatus(StrEnum):
    ONLINE = "ONLINE"
    BUSY = "BUSY"
    OFFLINE = "OFFLINE"


class ArtifactKind(StrEnum):
    INGEST_MANIFEST = "INGEST_MANIFEST"
    INGEST_SUMMARY = "INGEST_SUMMARY"
    INGEST_ARTIFACTS = "INGEST_ARTIFACTS"
    INGEST_EXCLUDED_ITEMS = "INGEST_EXCLUDED_ITEMS"
    INGEST_DUPLICATE_GROUPS = "INGEST_DUPLICATE_GROUPS"
    INGEST_PRIMARY_CANDIDATES = "INGEST_PRIMARY_CANDIDATES"
    INGEST_REFERENCE_CANDIDATES = "INGEST_REFERENCE_CANDIDATES"
    INGEST_SENSITIVE_ITEMS = "INGEST_SENSITIVE_ITEMS"
    INGEST_ISSUES = "INGEST_ISSUES"
    SOURCE_MOUNTS = "SOURCE_MOUNTS"
    CLI_LOG = "CLI_LOG"
