"""create p1-1 platform schema

Revision ID: 2c13448999a3
Revises:
Create Date: 2026-07-16 01:26:36.393823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c13448999a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deduplication_key', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', name='outbox_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('publish_attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('deduplication_key', name='uq_outbox_deduplication_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING_FOR_APPROVAL', 'RUNNING', 'BLOCKED', 'COMPLETED', 'CANCELLED', 'FAILED', name='task_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('capability_pack', sa.String(length=120), nullable=False),
    sa.Column('source_mount_path', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('worker_instances',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'BUSY', 'OFFLINE', name='worker_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_node_run_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hostname', sa.String(length=240), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_instances'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('INGEST_MANIFEST', 'INGEST_SUMMARY', 'INGEST_ARTIFACTS', 'INGEST_EXCLUDED_ITEMS', 'INGEST_DUPLICATE_GROUPS', 'INGEST_PRIMARY_CANDIDATES', 'INGEST_REFERENCE_CANDIDATES', 'INGEST_SENSITIVE_ITEMS', 'INGEST_ISSUES', 'SOURCE_MOUNTS', 'CLI_LOG', name='artifact_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_artifacts_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_table('human_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.Enum('TASK_START', name='approval_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('submitted_by', sa.String(length=160), nullable=False),
    sa.Column('decided_by', sa.String(length=160), nullable=True),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='approval_decision', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_human_approvals_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_approvals')),
    sa.UniqueConstraint('task_id', 'approval_type', name='uq_task_approval_type')
    )
    op.create_index(op.f('ix_human_approvals_task_id'), 'human_approvals', ['task_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('definition_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_APPROVAL', 'RUNNING', 'BLOCKED', 'COMPLETED', 'FAILED', name='workflow_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_workflow_runs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_index(op.f('ix_workflow_runs_task_id'), 'workflow_runs', ['task_id'], unique=False)
    op.create_table('node_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'QUEUED', 'RUNNING', 'WAITING_FOR_APPROVAL', 'SUCCEEDED', 'FAILED', 'RETRYING', 'BLOCKED', 'INVALIDATED', name='node_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('execution_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('current_output_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_node_runs_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_runs')),
    sa.UniqueConstraint('workflow_run_id', 'node_key', name='uq_workflow_run_node_key')
    )
    op.create_index(op.f('ix_node_runs_workflow_run_id'), 'node_runs', ['workflow_run_id'], unique=False)
    op.create_table('node_execution_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=160), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', 'ABANDONED', name='attempt_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], name=op.f('fk_node_execution_attempts_node_run_id_node_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_execution_attempts')),
    sa.UniqueConstraint('node_run_id', 'attempt_number', name='uq_node_attempt_number')
    )
    op.create_index(op.f('ix_node_execution_attempts_node_run_id'), 'node_execution_attempts', ['node_run_id'], unique=False)
    op.create_table('worker_leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=160), nullable=False),
    sa.Column('lease_token', sa.String(length=180), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'RELEASED', name='lease_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], name=op.f('fk_worker_leases_node_run_id_node_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_leases')),
    sa.UniqueConstraint('lease_token', name=op.f('uq_worker_leases_lease_token'))
    )
    op.create_index(op.f('ix_worker_leases_node_run_id'), 'worker_leases', ['node_run_id'], unique=False)
    op.create_index('uq_worker_leases_active_node', 'worker_leases', ['node_run_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('artifact_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('relative_storage_path', sa.String(length=1200), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('producer_attempt_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_versions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_attempt_id'], ['node_execution_attempts.id'], name=op.f('fk_artifact_versions_producer_attempt_id_node_execution_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_versions')),
    sa.UniqueConstraint('artifact_id', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_artifact_versions_artifact_id'), 'artifact_versions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_producer_attempt_id'), 'artifact_versions', ['producer_attempt_id'], unique=False)
    op.create_table('node_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['node_execution_attempts.id'], name=op.f('fk_node_run_logs_attempt_id_node_execution_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], name=op.f('fk_node_run_logs_node_run_id_node_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_run_logs')),
    sa.UniqueConstraint('node_run_id', 'sequence', name='uq_node_log_sequence')
    )
    op.create_index(op.f('ix_node_run_logs_node_run_id'), 'node_run_logs', ['node_run_id'], unique=False)
    op.create_table('node_run_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_version_id', sa.UUID(), nullable=False),
    sa.Column('output_role', sa.String(length=120), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_node_run_outputs_artifact_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], name=op.f('fk_node_run_outputs_node_run_id_node_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_run_outputs')),
    sa.UniqueConstraint('node_run_id', 'artifact_version_id', 'output_role', name='uq_node_output_version_role')
    )
    op.create_index(op.f('ix_node_run_outputs_node_run_id'), 'node_run_outputs', ['node_run_id'], unique=False)
    op.create_index('uq_node_outputs_current_role', 'node_run_outputs', ['node_run_id', 'output_role'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_node_outputs_current_role', table_name='node_run_outputs', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_node_run_outputs_node_run_id'), table_name='node_run_outputs')
    op.drop_table('node_run_outputs')
    op.drop_index(op.f('ix_node_run_logs_node_run_id'), table_name='node_run_logs')
    op.drop_table('node_run_logs')
    op.drop_index(op.f('ix_artifact_versions_producer_attempt_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_artifact_id'), table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index('uq_worker_leases_active_node', table_name='worker_leases', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_worker_leases_node_run_id'), table_name='worker_leases')
    op.drop_table('worker_leases')
    op.drop_index(op.f('ix_node_execution_attempts_node_run_id'), table_name='node_execution_attempts')
    op.drop_table('node_execution_attempts')
    op.drop_index(op.f('ix_node_runs_workflow_run_id'), table_name='node_runs')
    op.drop_table('node_runs')
    op.drop_index(op.f('ix_workflow_runs_task_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_human_approvals_task_id'), table_name='human_approvals')
    op.drop_table('human_approvals')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('worker_instances')
    op.drop_table('tasks')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
